Repository apache/shardingsphere-plugin, pull requests merged in 2023-10, with the labels that each got.

#12 Update README.md
  README.md
Labels: documentation

#13 Refactor : update dependencies
  pom.xml
Labels: build

#14 Add : add release note
  RELEASE-NOTE.md
Labels: documentation

#16 Refactor : uniform the plugin naming
  RELEASE-NOTE.md
Labels: documentation

#17 Update README.md
  README.md
Labels: documentation

#18 Add : add release related config
  pom.xml
Labels: build

#19 Add : add version property for shardingsphere dependencies
  features/encrypt/like/pom.xml
  features/encrypt/rc4/pom.xml
  features/encrypt/sm/pom.xml
  features/sharding/cosid/pom.xml
  features/sharding/nanoid/pom.xml
  infra/data-source-pool/c3p0/pom.xml
  infra/data-source-pool/dbcp/pom.xml
  jdbc/driver/apollo/pom.xml
  mode/cluster/repository/nacos/pom.xml
  pom.xml
Labels: build

#20 Refactor : update the version of project
  features/encrypt/like/pom.xml
  features/encrypt/pom.xml
  features/encrypt/rc4/pom.xml
  features/encrypt/sm/pom.xml
  features/pom.xml
  features/sharding/cosid/pom.xml
  features/sharding/nanoid/pom.xml
  features/sharding/pom.xml
  infra/data-source-pool/c3p0/pom.xml
  infra/data-source-pool/dbcp/pom.xml
  infra/data-source-pool/pom.xml
  infra/pom.xml
  jdbc/driver/apollo/pom.xml
  jdbc/driver/pom.xml
  jdbc/pom.xml
  mode/cluster/pom.xml
  mode/cluster/repository/nacos/pom.xml
  mode/cluster/repository/pom.xml
  mode/pom.xml
  pom.xml
Labels: type: refactor
