Repository apache/shardingsphere-plugin, pull requests merged in 2023-09, with the labels that each got.

#1 add asf yaml config and LICENSE
  .asf.yaml
  .gitignore
  .idea/icon.png
  .licenserc.yaml
  LICENSE
Labels: build

#5 Move rc4, like, nacos and apollo spi implementation to shardingsphere plugin
  features/encrypt/like/pom.xml
  features/encrypt/like/src/main/java/org/apache/shardingsphere/encrypt/like/algorithm/CharDigestLikeEncryptAlgorithm.java
  features/encrypt/like/src/main/resources/META-INF/services/org.apache.shardingsphere.encrypt.spi.EncryptAlgorithm
  features/encrypt/like/src/main/resources/algorithm/like/common_chinese_character.dict
  features/encrypt/like/src/test/java/org/apache/shardingsphere/encrypt/like/algorithm/CharDigestLikeEncryptAlgorithmTest.java
  features/encrypt/rc4/pom.xml
  features/encrypt/rc4/src/main/java/org/apache/shardingsphere/encrypt/rc4/algorithm/RC4EncryptAlgorithm.java
  features/encrypt/rc4/src/main/resources/META-INF/services/org.apache.shardingsphere.encrypt.spi.EncryptAlgorithm
  features/encrypt/rc4/src/test/java/org/apache/shardingsphere/encrypt/rc4/algorithm/RC4EncryptAlgorithmTest.java
  jdbc/driver/pom.xml
  jdbc/driver/src/main/java/org/apache/shardingsphere/jdbc/driver/ApolloURLProvider.java
  jdbc/driver/src/main/resources/META-INF/services/org.apache.shardingsphere.driver.jdbc.core.driver.ShardingSphereURLProvider
  jdbc/pom.xml
  mode/cluster/pom.xml
  mode/cluster/repository/nacos/pom.xml
  mode/cluster/repository/nacos/src/main/java/org/apache/shardingsphere/mode/repository/cluster/nacos/NacosRepository.java
  mode/cluster/repository/nacos/src/main/java/org/apache/shardingsphere/mode/repository/cluster/nacos/entity/KeyValue.java
  mode/cluster/repository/nacos/src/main/java/org/apache/shardingsphere/mode/repository/cluster/nacos/entity/ServiceController.java
  mode/cluster/repository/nacos/src/main/java/org/apache/shardingsphere/mode/repository/cluster/nacos/entity/ServiceMetaData.java
  mode/cluster/repository/nacos/src/main/java/org/apache/shardingsphere/mode/repository/cluster/nacos/listener/NamingEventListener.java
  mode/cluster/repository/nacos/src/main/java/org/apache/shardingsphere/mode/repository/cluster/nacos/listener/WatchData.java
  mode/cluster/repository/nacos/src/main/java/org/apache/shardingsphere/mode/repository/cluster/nacos/props/NacosProperties.java
  mode/cluster/repository/nacos/src/main/java/org/apache/shardingsphere/mode/repository/cluster/nacos/props/NacosPropertyKey.java
  mode/cluster/repository/nacos/src/main/java/org/apache/shardingsphere/mode/repository/cluster/nacos/util/NacosMetaDataUtils.java
  mode/cluster/repository/nacos/src/main/resources/META-INF/services/org.apache.shardingsphere.mode.repository.cluster.ClusterPersistRepository
  mode/cluster/repository/nacos/src/test/java/org/apache/shardingsphere/mode/repository/cluster/nacos/NacosRepositoryTest.java
  mode/cluster/repository/nacos/src/test/java/org/apache/shardingsphere/mode/repository/cluster/nacos/props/NacosPropertiesTest.java
  mode/cluster/repository/pom.xml
  mode/pom.xml
  pom.xml
Labels: enhancement

#6 Optimize pom and add doc for spi implementation
  README.md
  README_ZH.md
  features/encrypt/like/pom.xml
  features/encrypt/pom.xml
  features/encrypt/rc4/pom.xml
  features/encrypt/sm/pom.xml
  features/pom.xml
  features/sharding/cosid/pom.xml
  features/sharding/nanoid/pom.xml
  features/sharding/pom.xml
  pom.xml
Labels: documentation

#8 Update readme doc
  README.md
  README_ZH.md
Labels: documentation

#9 Add : add mvnw to plugin repository
  .mvn/jvm.config
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: build
