Repository apache/shardingsphere-plugin, pull requests merged in 2024-02, with the labels that each got.

#25 Rename ApolloURLProvider to ApolloURLLoader
  features/encrypt/like/src/main/java/org/apache/shardingsphere/encrypt/like/algorithm/CharDigestLikeEncryptAlgorithm.java
  features/encrypt/like/src/test/java/org/apache/shardingsphere/encrypt/like/algorithm/CharDigestLikeEncryptAlgorithmTest.java
  features/encrypt/rc4/src/main/java/org/apache/shardingsphere/encrypt/rc4/algorithm/RC4EncryptAlgorithm.java
  features/encrypt/rc4/src/test/java/org/apache/shardingsphere/encrypt/rc4/algorithm/RC4EncryptAlgorithmTest.java
  features/encrypt/sm/src/main/java/org/apache/shardingsphere/encrypt/sm/algorithm/SM3EncryptAlgorithm.java
  features/encrypt/sm/src/main/java/org/apache/shardingsphere/encrypt/sm/algorithm/SM4EncryptAlgorithm.java
  features/encrypt/sm/src/test/java/org/apache/shardingsphere/encrypt/sm/algorithm/SM3EncryptAlgorithmTest.java
  features/encrypt/sm/src/test/java/org/apache/shardingsphere/encrypt/sm/algorithm/SM4EncryptAlgorithmTest.java
  features/sharding/cosid/pom.xml
  features/sharding/cosid/src/main/java/org/apache/shardingsphere/sharding/cosid/algorithm/keygen/CosIdKeyGenerateAlgorithm.java
  features/sharding/cosid/src/main/java/org/apache/shardingsphere/sharding/cosid/algorithm/keygen/CosIdSnowflakeKeyGenerateAlgorithm.java
  features/sharding/cosid/src/main/resources/META-INF/services/org.apache.shardingsphere.keygen.core.algorithm.KeyGenerateAlgorithm
  features/sharding/cosid/src/test/java/org/apache/shardingsphere/sharding/cosid/algorithm/keygen/CosIdKeyGenerateAlgorithmTest.java
  features/sharding/cosid/src/test/java/org/apache/shardingsphere/sharding/cosid/algorithm/keygen/CosIdSnowflakeKeyGenerateAlgorithmTest.java
  features/sharding/nanoid/pom.xml
  features/sharding/nanoid/src/main/java/org/apache/shardingsphere/sharding/nanoid/algorithm/keygen/NanoIdKeyGenerateAlgorithm.java
  features/sharding/nanoid/src/main/resources/META-INF/services/org.apache.shardingsphere.keygen.core.algorithm.KeyGenerateAlgorithm
  features/sharding/nanoid/src/test/java/org/apache/shardingsphere/sharding/nanoid/algorithm/keygen/NanoIdKeyGenerateAlgorithmTest.java
  infra/pom.xml
  infra/url/apollo/pom.xml
  infra/url/apollo/src/main/java/org/apache/shardingsphere/jdbc/driver/ApolloURLLoader.java
  infra/url/apollo/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.url.ShardingSphereURLLoader
  infra/url/apollo/src/test/java/org/apache/shardingsphere/jdbc/driver/ApolloURLLoaderTest.java
  infra/url/pom.xml
  jdbc/driver/apollo/pom.xml
  jdbc/driver/apollo/src/main/java/org/apache/shardingsphere/jdbc/driver/ApolloURLProvider.java
  pom.xml
Labels: type: refactor

#26 Adapt to the latest code
  features/encrypt/like/src/main/java/org/apache/shardingsphere/encrypt/like/algorithm/CharDigestLikeEncryptAlgorithm.java
  features/encrypt/like/src/test/java/org/apache/shardingsphere/encrypt/like/algorithm/CharDigestLikeEncryptAlgorithmTest.java
  features/encrypt/rc4/src/main/java/org/apache/shardingsphere/encrypt/rc4/algorithm/RC4EncryptAlgorithm.java
  features/encrypt/rc4/src/test/java/org/apache/shardingsphere/encrypt/rc4/algorithm/RC4EncryptAlgorithmTest.java
  features/encrypt/sm/src/main/java/org/apache/shardingsphere/encrypt/sm/algorithm/SM3EncryptAlgorithm.java
  features/encrypt/sm/src/main/java/org/apache/shardingsphere/encrypt/sm/algorithm/SM4EncryptAlgorithm.java
  features/encrypt/sm/src/test/java/org/apache/shardingsphere/encrypt/sm/algorithm/SM3EncryptAlgorithmTest.java
  features/encrypt/sm/src/test/java/org/apache/shardingsphere/encrypt/sm/algorithm/SM4EncryptAlgorithmTest.java
  features/sharding/cosid/src/main/java/org/apache/shardingsphere/sharding/cosid/algorithm/keygen/CosIdKeyGenerateAlgorithm.java
  features/sharding/cosid/src/main/java/org/apache/shardingsphere/sharding/cosid/algorithm/keygen/CosIdSnowflakeKeyGenerateAlgorithm.java
  features/sharding/cosid/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.algorithm.keygen.core.KeyGenerateAlgorithm
  features/sharding/cosid/src/test/java/org/apache/shardingsphere/sharding/cosid/algorithm/keygen/CosIdKeyGenerateAlgorithmTest.java
  features/sharding/cosid/src/test/java/org/apache/shardingsphere/sharding/cosid/algorithm/keygen/CosIdSnowflakeKeyGenerateAlgorithmTest.java
  features/sharding/nanoid/src/main/java/org/apache/shardingsphere/sharding/nanoid/algorithm/keygen/NanoIdKeyGenerateAlgorithm.java
  features/sharding/nanoid/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.algorithm.keygen.core.KeyGenerateAlgorithm
  features/sharding/nanoid/src/test/java/org/apache/shardingsphere/sharding/nanoid/algorithm/keygen/NanoIdKeyGenerateAlgorithmTest.java
  infra/url/apollo/src/main/java/org/apache/shardingsphere/jdbc/driver/ApolloURLLoader.java
  infra/url/apollo/src/main/resources/META-INF/services/org.apache.shardingsphere.infra.url.spi.ShardingSphereURLLoader
Labels: enhancement

#28 Add mode consul plugin in ShardingSphere Plugin repository
  README.md
  README_ZH.md
  mode/cluster/repository/consul/pom.xml
  mode/cluster/repository/consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/ConsulRepository.java
  mode/cluster/repository/consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/ShardingSphereConsulClient.java
  mode/cluster/repository/consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/ShardingSphereQueryParams.java
  mode/cluster/repository/consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/lock/ConsulDistributedLock.java
  mode/cluster/repository/consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/lock/ConsulDistributedLockCreator.java
  mode/cluster/repository/consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/props/ConsulProperties.java
  mode/cluster/repository/consul/src/main/java/org/apache/shardingsphere/mode/repository/cluster/consul/props/ConsulPropertyKey.java
  mode/cluster/repository/consul/src/main/resources/META-INF/services/org.apache.shardingsphere.mode.repository.cluster.ClusterPersistRepository
  mode/cluster/repository/consul/src/main/resources/META-INF/services/org.apache.shardingsphere.mode.repository.cluster.lock.creator.DistributedLockCreator
  mode/cluster/repository/consul/src/test/java/org/apache/shardingsphere/mode/repository/cluster/consul/ConsulRepositoryTest.java
  mode/cluster/repository/consul/src/test/java/org/apache/shardingsphere/mode/repository/cluster/consul/props/ConsulPropertiesTest.java
  mode/cluster/repository/pom.xml
Labels: mode: cluster

#29 Add kernel sql translator jooq plugin in ShardingSphere Plugin repository
  README.md
  README_ZH.md
  kernel/pom.xml
  kernel/sql-translator/jooq/pom.xml
  kernel/sql-translator/jooq/src/main/java/org/apache/shardingsphere/sqltranslator/jooq/JooQDialectRegistry.java
  kernel/sql-translator/jooq/src/main/java/org/apache/shardingsphere/sqltranslator/jooq/JooQSQLTranslator.java
  kernel/sql-translator/jooq/src/main/resources/META-INF/services/org.apache.shardingsphere.sqltranslator.spi.SQLTranslator
  kernel/sql-translator/pom.xml
  pom.xml
Labels: in: kernel, type: refactor

#32 Remove shardingsphere-test-util dependency to solve build fail
  features/sharding/cosid/pom.xml
  infra/algorithm/key-generator/cosid/pom.xml
  infra/data-source-pool/c3p0/pom.xml
  infra/data-source-pool/c3p0/src/test/java/org/apache/shardingsphere/infra/datasource/pool/c3p0/creator/C3P0DataSourcePoolCreatorTest.java
  infra/data-source-pool/dbcp/pom.xml
  infra/data-source-pool/dbcp/src/test/java/org/apache/shardingsphere/infra/datasource/pool/dbcp/creator/DBCPDataSourcePoolCreatorTest.java
  infra/url/apollo/pom.xml
  infra/url/apollo/src/test/java/org/apache/shardingsphere/jdbc/driver/ApolloURLLoaderTest.java
  mode/cluster/repository/consul/pom.xml
  mode/cluster/repository/nacos/pom.xml
  mode/cluster/repository/nacos/src/test/java/org/apache/shardingsphere/mode/repository/cluster/nacos/NacosRepositoryTest.java
  mode/cluster/repository/nacos/src/test/java/org/apache/shardingsphere/mode/repository/cluster/nacos/props/NacosPropertiesTest.java
Labels: build, type: dependencies

#34 Add url loader documentation
  README.md
  README_ZH.md
Labels: documentation
